armv6l workaround
Using `fs.createReadStream()` with a path of an input device will throw the follow error in **Raspberry Pi Zero W**, **Raspbian Lite (stretch)**, **node.js v9.5.0**.

```
events.js:137
      throw er; // Unhandled 'error' event
      ^

Error: ESPIPE: invalid seek, read
```

According to the doc, using the `options.fd` will skip the initial `seek` command when `options.start` is `undefined`.

I tested this change in my Raspberry Pi and Macbook.